# -*- coding: utf-8 -*-
"""european_soccer_live_matches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIY-5RgwExbphtyNoBGt6cLi25DC2vzh
"""

import requests
import pandas as pd

# 1. API Bilgilerini Tanımla
url = "https://v3.football.api-sports.io/fixtures"
headers = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "0f006a6e45f9c3502c156a1c08bfe68b"
}
# Sadece canlı oynanan maçları filtrelemek için
query_params = {'live': 'all'}
# 2. API'den Canlı Veriyi Çekmek için
response = requests.get(url, headers=headers, params=query_params)
data=response.json()

# 3. Gelen Karışık Veriyi Pandas ile Temiz Bir Tabloya Çevirmek
live_matches = []
for item in data['response']:
  live_matches.append({
      "Lig": item['league']['name'],
      "Ev_Sahibi": item['teams']['home']['name'],
      "Deplasman": item['teams']['away']['name'],
      "Ev_Gol": item['goals']['home'],
      "Dep_Gol": item['goals']['away'],
      "Dakika": item['fixture']['status']['elapsed']
  })

  df = pd.DataFrame(live_matches)
  print(df.head())



!pip install streamlit requests pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import pandas as pd
# import time
# import datetime
# 
# st.set_page_config(page_title="European Leagues Live Scores", layout="wide")
# st.title("⚽ European Major Leagues - Live Score Panel")
# 
# @st.fragment(run_every=15)
# def live_score_stream():
#     url = "https://v3.football.api-sports.io/fixtures"
# 
#     # API Key'ini saf string haline getirip encode hatasını tamamen engelliyoruz
#     raw_key = "0f006a6e45f9c3502c156a1c08bfe68b"
#     clean_key = str(raw_key).strip().encode('utf-8').decode('latin-1')
# 
#     headers = {
#         'x-rapidapi-host': "v3.football.api-sports.io",
#         'x-rapidapi-key': clean_key
#     }
# 
#     today_date = datetime.date.today().strftime('%Y-%m-%d')
#     query_params = {"date": today_date}
# 
#     try:
#         response = requests.get(url, headers=headers, params=query_params)
#         data = response.json()
# 
#         european_leagues = ["Premier League", "La Liga", "Serie A", "Bundesliga", "Ligue 1", "Eredivisie"]
#         match_list = []
#         all_other_matches = []
# 
#         for item in data.get('response', []):
#             league_name = str(item['league']['name'])
# 
#             home_goals = item['goals']['home'] if item['goals']['home'] is not None else 0
#             away_goals = item['goals']['away'] if item['goals']['away'] is not None else 0
#             elapsed_time = f"{item['fixture']['status']['elapsed']}'" if item['fixture']['status']['elapsed'] else "Not Started"
# 
#             match_data = {
#                 "league": league_name,
#                 "country": str(item['league']['country']),
#                 "home_team": str(item['teams']['home']['name']),
#                 "away_team": str(item['teams']['away']['name']),
#                 "score": f"{home_goals} - {away_goals}",
#                 "elapsed_time": str(elapsed_time)
#             }
# 
#             if league_name in european_leagues:
#                 match_list.append(match_data)
#             else:
#                 all_other_matches.append(match_data)
# 
#         if match_list:
#             df = pd.DataFrame(match_list)
#             st.subheader("🔥 Live & Upcoming Major European Matches")
#             st.metric(label="Total Major Matches Today", value=len(df))
#             st.dataframe(df, use_container_width=True, hide_index=True)
#         else:
#             st.info("There are no matches scheduled or playing in the selected Major European leagues today.")
#             if all_other_matches:
#                 st.write("---")
#                 st.subheader("🌍 Sample Live / Today's Matches Across Global Leagues (Demo Mode)")
#                 df_fallback = pd.DataFrame(all_other_matches[:10])
#                 st.dataframe(df_fallback, use_container_width=True, hide_index=True)
# 
#     except Exception as e:
#         st.error(f"Error: {e}")
# 
#     st.caption(f"Last Updated At: {time.strftime('%H:%M:%S')}")
# 
# live_score_stream()

!streamlit run app.py

!npm install -g localtunnel

import urllib
print("Sitenizin Giriş Şifresi (Tunnel Password):", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf-8').strip())

!streamlit run app.py & npx localtunnel --port 8501